language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- chaos run experiment.json --settings settings.yaml
before_install:
- openssl aes-256-cbc -K $encrypted_fdb844fae20b_key -iv $encrypted_fdb844fae20b_iv
  -in settings.yaml.enc -out settings.yaml -d
